version: "3"
services:
  springboot-app:
    container_name: smartcine-springboot-app
    restart: on-failure:3
    networks:
      - smartcine-network
    build:
      context: . # use the current directory as the build contexts
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/smartcine
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dbsmartcinedinhvl
      SERVER_PORT: 9999 # internal springboot app port
